version: 2
updates:
- package-ecosystem: pip
  labels:
    - "src"
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  groups:
    source-packages:
      patterns:
        - "*"
- package-ecosystem: pip
  labels:
    - "docs"
  directory: "/docs"
  schedule:
    interval: daily
    time: "04:00"
  groups:
    docs-packages:
      patterns:
        - "*"
