repos:
  -   repo: local
      hooks:
      -   id: python-hook
          name: python-hook
          entry: python scripts/pre-commit.py
          language: python
          pass_filenames: false
  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'  # add version here
    hooks:
      - id: poetry-check
        args: [ "-C", "." ]
      - id: poetry-lock
        args: [ "-C", "." ]
      - id: poetry-export
        name: source-dependencies
        args: [ "--without", "docs,test", "-f", "requirements.txt" ]
        verbose: true
      - id: poetry-export
        name: docs-dependencies
        args: [ "--with", "docs", "-C", "./docs", "-f", "requirements.txt", "-o", "./docs/requirements.txt" ]
        verbose: true
      - id: poetry-install
        args: [ "-C", "." ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: |
            (?x)^(
                requirements.txt|
                docs/requirements.txt
            )$
      - id: trailing-whitespace
        exclude: |
            (?x)^(
                requirements.txt|
                docs/requirements.txt
            )$
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
